# { application-dev, application-qa, application-prod }
# spring.profiles.active=cat,qa,dev,prod # The last item will be run, In this case prod
# spring.profiles.active=cat,dev # Unique item (dev) then it will be run
spring:
  profiles:
    active:
      - bird
      - qa

server:
  port: 8000

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: qa

server:
  port: 8091

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8092
